version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/app
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    # depends_on:
    #   - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    ports:
      - "3306:3306"
